annotations:
  artifacthub.io/changes: |
    - "[Changed]: Upgrade ArgoRollouts to v1.3.1"
apiVersion: v2
appVersion: v1.3.1
description: A Helm chart for Argo Rollouts
home: https://github.com/argoproj/argo-helm
icon: https://argoproj.github.io/argo-rollouts/assets/logo.png
keywords:
- argoproj
- argo-rollouts
maintainers:
- name: argoproj
  url: https://argoproj.github.io/
name: argo-rollouts
sources:
- https://github.com/argoproj/argo-rollouts
version: 2.21.1
